# Generated by Django 5.2.4 on 2025-07-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_discount_product_order_orderitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
    ]
