# Generated by Django 5.2.4 on 2025-07-09 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_adress_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='emial',
            new_name='email',
        ),
    ]
